version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: academia_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ^2gS-F9m7)
      MYSQL_DATABASE: academia
      MYSQL_USER: loja
      MYSQL_PASSWORD: loja123
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
